version: '3.1'
services:
  registry:
    build: ./registry
    ports:
      - "8761:8761"
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka
  apigateway:
    build: ./APIgateway
    ports:
      - "4000:4000"
    links:
      - registry
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka/
  vehicledata:
    build: ./VEHICLEdata
    ports:
      - "8001:8001"
    links:
      - registry
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka/
    volumes:
      - ~/.config/:/root/.config
      #TODO: cannot connect to registry/eureka
  datasimulator:
      build: ./data-simulator
      ports:
        - "8138:8138"
      environment:
        SPRING_PROFILES_ACTIVE: dev
      volumes:
        - ~/.config/:/root/.config
      restart: always
      links:
        - vehicledata
        #TODO: cannot connect to registry/eureka
  notyfier:
    build: ./NOTYfier
    ports:
      - "8248:8248"
    links:
      - registry
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka/
    volumes:
      - ~/.config/:/root/.config
      #TODO: cannot connect to registry/eureka
  govstat:
    build: ./GOVstat
    ports:
      - "8242:8242"
    links:
      - registry
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka/
    volumes:
      - ~/.config/:/root/.config
      #TODO: cannot connect to registry/eureka
  mongo:
    build: ./database
    container_name: dse_mongo_db
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/db:/data/db
      - $HOME/data/bkp:/data/bkp
    restart: always

