version: '3.1'
services:
  registry:
    build: ./registry
    container_name: dse_registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:8123/
  admin:
    build: ./admin
    container_name: dse_admin
    ports:
      - "8123:8123"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    depends_on:
      - registry
  gateway:
    build: ./gateway
    container_name: dse_gateway
    ports:
      - "4000:4000"
    environment:
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:8123/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    depends_on:
      - registry
      - admin
  dashboard:
    build: ./monitoring
    container_name: dse_monitoring
    ports:
      - "8080:8080"
    environment:
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:8123/
  demo-service:
    build: ./demo-service
    container_name: dse_demo-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:8123/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    depends_on:
      - registry
      - admin
  demo-client:
    build: ./demo-client
    container_name: dse_demo-client
    ports:
      - "9091:9091"
    environment:
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:8123/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    depends_on:
      - registry
      - admin
  mongo:
    build: ./database
    container_name: dse_mongo_db
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/db:/data/db
      - $HOME/data/bkp:/data/bkp
    restart: always
  store-front-ui:
    build: ./StoreFrontUI
    restart: always
    container_name: dse_frontend
    ports:
      - 4200:4200