version: '3.1'
services:
  mongo:
    build: ./database
    container_name: dse_mongo_db
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/db:/data/db
      - $HOME/data/bkp:/data/bkp
    restart: always
  store-front-ui:
    build: ./StoreFrontUI
    restart: always
    container_name: dse_frontend
    ports:
      - 4200:4200