version: '3.1'
services:
  registry:
    build: ./registry
    ports:
      - "8761:8761"
    restart: always
  apigateway:
    build: ./APIgateway
    ports:
      - "4000:4000"
    restart: always
    links:
      - registry
    environment:
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka/